#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Neuronales_Netz.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gluegen-rt-natives-linux-aarch64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-macosx-universal.jar:$APPDIR/lib/gluegen-rt-natives-windows-amd64.jar:$APPDIR/lib/gluegen-rt-natives-windows-i586.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-aarch64.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/jogl-all-natives-macosx-universal.jar:$APPDIR/lib/jogl-all-natives-windows-amd64.jar:$APPDIR/lib/jogl-all-natives-windows-i586.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/Drop.jar" Neuronales_Netz "$@"
